-- Run this in Supabase SQL Editor before starting the API.
-- The API uses the service role key, so RLS protects direct client access
-- while the trusted backend can serve the existing API contract.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists users_username_lower_idx
  on public.users (lower(username));

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  sub text not null default '',
  icon text not null default '💪',
  color text not null default '#7c5cff',
  created_at timestamptz not null default now()
);

create table if not exists public.habit_history (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete cascade,
  date date not null,
  unique (habit_id, date)
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  from_user_id bigint not null references public.users(id) on delete cascade,
  to_user_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  unique (from_user_id, to_user_id)
);

alter table public.users enable row level security;
alter table public.habits enable row level security;
alter table public.habit_history enable row level security;
alter table public.friend_requests enable row level security;

-- Keep identity sequences correct if existing local data is migrated with explicit IDs.
select setval(pg_get_serial_sequence('public.users', 'id'), coalesce(max(id), 0) + 1, false) from public.users;
select setval(pg_get_serial_sequence('public.habits', 'id'), coalesce(max(id), 0) + 1, false) from public.habits;
select setval(pg_get_serial_sequence('public.habit_history', 'id'), coalesce(max(id), 0) + 1, false) from public.habit_history;
select setval(pg_get_serial_sequence('public.friend_requests', 'id'), coalesce(max(id), 0) + 1, false) from public.friend_requests;
