-- Free architecture: Supabase Auth + direct browser access.
-- Run this in Supabase SQL Editor.
-- In Supabase Auth settings, disable email confirmation because this app uses
-- username-based synthetic email identities (username@lockin.local).

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now()
);

create unique index if not exists users_username_lower_idx
  on public.users (lower(username));

create table if not exists public.habits (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  sub text not null default '',
  icon text not null default '💪',
  color text not null default '#7c5cff',
  created_at timestamptz not null default now()
);

create table if not exists public.habit_history (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete cascade,
  date date not null,
  unique (habit_id, date)
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  from_user_id bigint not null references public.users(id) on delete cascade,
  to_user_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamptz not null default now(),
  unique (from_user_id, to_user_id)
);

alter table public.users enable row level security;
alter table public.habits enable row level security;
alter table public.habit_history enable row level security;
alter table public.friend_requests enable row level security;

drop policy if exists users_select_authenticated on public.users;
create policy users_select_authenticated on public.users
  for select to authenticated using (true);

drop policy if exists users_insert_self on public.users;
create policy users_insert_self on public.users
  for insert to authenticated with check (auth_user_id = auth.uid());

drop policy if exists users_update_self on public.users;
create policy users_update_self on public.users
  for update to authenticated using (auth_user_id = auth.uid()) with check (auth_user_id = auth.uid());

drop policy if exists habits_owner_access on public.habits;
create policy habits_owner_access on public.habits
  for all to authenticated
  using (exists (select 1 from public.users u where u.id = habits.user_id and u.auth_user_id = auth.uid()))
  with check (exists (select 1 from public.users u where u.id = habits.user_id and u.auth_user_id = auth.uid()));

drop policy if exists history_owner_access on public.habit_history;
create policy history_owner_access on public.habit_history
  for all to authenticated
  using (exists (
    select 1 from public.habits h
    join public.users u on u.id = h.user_id
    where h.id = habit_history.habit_id and u.auth_user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.habits h
    join public.users u on u.id = h.user_id
    where h.id = habit_history.habit_id and u.auth_user_id = auth.uid()
  ));

drop policy if exists friend_requests_access on public.friend_requests;
create policy friend_requests_access on public.friend_requests
  for all to authenticated
  using (exists (
    select 1 from public.users u
    where (u.id = friend_requests.from_user_id or u.id = friend_requests.to_user_id)
      and u.auth_user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.users u
    where friend_requests.from_user_id = u.id and u.auth_user_id = auth.uid()
  ));

-- Keep identity sequences correct when importing explicit IDs.
select setval(pg_get_serial_sequence('public.users', 'id'), coalesce(max(id), 0) + 1, false) from public.users;
select setval(pg_get_serial_sequence('public.habits', 'id'), coalesce(max(id), 0) + 1, false) from public.habits;
select setval(pg_get_serial_sequence('public.habit_history', 'id'), coalesce(max(id), 0) + 1, false) from public.habit_history;
select setval(pg_get_serial_sequence('public.friend_requests', 'id'), coalesce(max(id), 0) + 1, false) from public.friend_requests;
